import os, json, re
from groq import Groq

GROQ_MODEL = "llama-3.3-70b-versatile"

def _clamp(x, lo=0.0, hi=1.0):
    return max(lo, min(hi, x))

# ---------- Signal 1: LLM ----------
def llm_signal(text):
    """Returns {'score': float|None, 'reasoning': str, 'error': str|None}."""
    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key:
        return {"score": None, "reasoning": "", "error": "missing_api_key"}
    try:
        client = Groq(api_key=api_key)
        prompt = (
            "You are an AI-content detector. Assess whether the TEXT below was "
            "written by a human or generated by an AI language model. Respond "
            "ONLY with valid JSON, no markdown, in this exact shape:\n"
            '{"ai_likelihood": <float 0..1>, "reasoning": "<one sentence>"}\n'
            "0 = certainly human, 1 = certainly AI.\n\n"
            f'TEXT:\n"""\n{text}\n"""'
        )
        resp = client.chat.completions.create(
            model=GROQ_MODEL,
            messages=[{"role": "user", "content": prompt}],
            temperature=0,
        )
        raw = resp.choices[0].message.content.strip()
        raw = re.sub(r"^```(json)?|```$", "", raw).strip()
        data = json.loads(raw)
        score = _clamp(float(data["ai_likelihood"]))
        return {"score": score, "reasoning": data.get("reasoning", ""), "error": None}
    except Exception as e:
        return {"score": None, "reasoning": "", "error": f"{type(e).__name__}: {e}"}

# ---- M3 TEMPORARY STUBS (replaced in M4/M5) ----
def stylometric_signal(text):
    return {"score": 0.5, "metrics": {}}

def combine_scores(llm_score, stylo_score):
    c = round(llm_score if llm_score is not None else 0.5, 3)
    return c, ("likely_ai" if c >= 0.75 else "likely_human" if c < 0.40 else "uncertain"), llm_score is None

def make_label(attribution, confidence):
    return f"[stub] {attribution} ({round(confidence*100)}%)"
