import os, json, re
from groq import Groq

GROQ_MODEL = "llama-3.3-70b-versatile"

def _clamp(x, lo=0.0, hi=1.0):
    return max(lo, min(hi, x))

# ---------- Signal 1: LLM ----------
def llm_signal(text):
    """Returns {'score': float|None, 'reasoning': str, 'error': str|None}."""
    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key:
        return {"score": None, "reasoning": "", "error": "missing_api_key"}
    try:
        client = Groq(api_key=api_key)
        prompt = (
            "You are an AI-content detector. Assess whether the TEXT below was "
            "written by a human or generated by an AI language model. Respond "
            "ONLY with valid JSON, no markdown, in this exact shape:\n"
            '{"ai_likelihood": <float 0..1>, "reasoning": "<one sentence>"}\n'
            "0 = certainly human, 1 = certainly AI.\n\n"
            f'TEXT:\n"""\n{text}\n"""'
        )
        resp = client.chat.completions.create(
            model=GROQ_MODEL,
            messages=[{"role": "user", "content": prompt}],
            temperature=0,
        )
        raw = resp.choices[0].message.content.strip()
        raw = re.sub(r"^```(json)?|```$", "", raw).strip()
        data = json.loads(raw)
        score = _clamp(float(data["ai_likelihood"]))
        return {"score": score, "reasoning": data.get("reasoning", ""), "error": None}
    except Exception as e:
        return {"score": None, "reasoning": "", "error": f"{type(e).__name__}: {e}"}


import statistics

# ---------- Signal 2: Stylometric ----------
def _sentences(text):
    return [p.strip() for p in re.split(r"[.!?]+", text) if p.strip()]

def _words(text):
    return re.findall(r"\b\w+\b", text.lower())

def stylometric_signal(text):
    words, sents = _words(text), _sentences(text)
    n_words = len(words)
    metrics = {}

    # 1. Burstiness: coefficient of variation of sentence lengths (in words)
    lengths = [len(_words(s)) for s in sents] or [0]
    mean_len = statistics.mean(lengths) if lengths else 0
    cv = (statistics.pstdev(lengths) / mean_len) if (len(lengths) > 1 and mean_len) else 0.0
    burst = _clamp((0.6 - cv) / 0.4)          # low variance -> AI

    # 2. Type-token ratio (vocabulary diversity)
    ttr = (len(set(words)) / n_words) if n_words else 0.0
    ttr_c = _clamp((0.75 - ttr) / 0.35)       # low diversity -> AI

    # 3. Punctuation density
    punct = len(re.findall(r"[,;:\-—()\"']", text))
    pdens = (punct / n_words) if n_words else 0.0
    punct_c = _clamp((0.18 - pdens) / 0.18)   # flat/sparse -> mildly AI

    score = round(_clamp(0.60 * burst + 0.25 * ttr_c + 0.15 * punct_c), 3)
    metrics.update({
        "sentence_count": len(sents), "mean_sentence_length": round(mean_len, 2),
        "sentence_length_cv": round(cv, 3), "type_token_ratio": round(ttr, 3),
        "punctuation_density": round(pdens, 3),
        "burst_component": round(burst, 3), "ttr_component": round(ttr_c, 3),
        "punct_component": round(punct_c, 3)})
    return {"score": score, "metrics": metrics}

# ---------- Confidence scoring ----------
LIKELY_AI, LIKELY_HUMAN = 0.75, 0.40

def classify(confidence):
    if confidence >= LIKELY_AI:   return "likely_ai"
    if confidence < LIKELY_HUMAN: return "likely_human"
    return "uncertain"

def combine_scores(llm_score, stylo_score):
    """Returns (confidence, attribution, degraded)."""
    if llm_score is None:
        # Degraded: one signal only. Never emit a high-confidence verdict.
        c = round(_clamp(0.40 + (stylo_score - 0.5) * 0.3), 3)
        return c, classify(c), True
    combined = 0.65 * llm_score + 0.35 * stylo_score
    # False-positive guard: don't call it AI unless BOTH signals lean AI.
    if stylo_score < 0.5 and combined >= LIKELY_AI:
        combined = 0.74
    combined = round(_clamp(combined), 3)
    return combined, classify(combined), False
